export const siteData = {
  gym: {
    name: 'Cycle House',
    tagline: 'RIDE. PUSH. REPEAT.',
    location: 'New York, NY',
    founded: '2016',
    phone: '(212) 555-0188',
    email: 'ride@cyclehouse.com',
    address: '145 W 28th St, New York, NY 10001',
    instagram: 'https://instagram.com/cyclehouse',
    hero_video: 'https://videos.pexels.com/video-files/3209828/3209828-uhd_2560_1440_25fps.mp4',
    hero_poster: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1600&q=80',
  },
  stats: [
    { value: '120+', label: 'BPM Peak' },
    { value: '45', label: 'Min Sessions' },
    { value: '12K+', label: 'Riders Strong' },
    { value: '98%', label: 'Would Return' },
  ],
  rideTypes: [
    {
      name: 'Power Ride',
      duration: '45 min',
      intensity: 'HIGH',
      description: 'Heavy resistance intervals timed to driving beats. Build raw cycling power and burn serious calories.',
      icon: '⚡',
    },
    {
      name: 'Rhythm Ride',
      duration: '45 min',
      intensity: 'MEDIUM',
      description: 'Choreographed movement synced to music. Upper body work woven throughout a full cardio flow.',
      icon: '🎵',
    },
    {
      name: 'Sprint Series',
      duration: '30 min',
      intensity: 'MAX',
      description: 'Short, explosive sprint intervals with near-zero recovery. Not for the faint-hearted.',
      icon: '🔥',
    },
    {
      name: 'Recovery Ride',
      duration: '45 min',
      intensity: 'LOW',
      description: 'Steady-state cardio in the zone 2 range. Active recovery that still moves the needle.',
      icon: '🌊',
    },
  ],
  schedule: [
    { day: 'MON', time: '6:00 AM', name: 'Power Ride', coach: 'Marcus', spots: 3 },
    { day: 'MON', time: '7:00 PM', name: 'Rhythm Ride', coach: 'Jade', spots: 8 },
    { day: 'TUE', time: '6:30 AM', name: 'Sprint Series', coach: 'Devon', spots: 1 },
    { day: 'WED', time: '12:00 PM', name: 'Power Ride', coach: 'Marcus', spots: 12 },
    { day: 'THU', time: '6:00 AM', name: 'Recovery Ride', coach: 'Jade', spots: 15 },
    { day: 'FRI', time: '6:00 PM', name: 'Rhythm Ride', coach: 'Devon', spots: 5 },
    { day: 'SAT', time: '9:00 AM', name: 'Sprint Series', coach: 'Marcus', spots: 0 },
    { day: 'SUN', time: '10:00 AM', name: 'Power Ride', coach: 'Jade', spots: 7 },
  ],
  coaches: [
    {
      name: 'Marcus Webb',
      role: 'Head Coach & Founder',
      bio: 'Former competitive cyclist turned indoor coach. Marcus built Cycle House from a single studio to NYC\'s premier ride destination.',
      rides: '3,400+',
    },
    {
      name: 'Jade Okafor',
      role: 'Rhythm Specialist',
      bio: 'Choreographer-turned-cyclist, Jade\'s classes feel like a dance party on two wheels. Her waitlists form within minutes of opening.',
      rides: '2,100+',
    },
    {
      name: 'Devon Cruz',
      role: 'Sprint Coach',
      bio: 'Performance athlete and sprint coach Devon designs the most data-driven workouts in the house. Clip in ready to suffer.',
      rides: '1,800+',
    },
  ],
  pricing: [
    {
      name: 'Single Ride',
      price: '$34',
      period: 'per class',
      features: ['1 class credit', 'Bike + shoes included', 'Digital metrics', 'Guest access'],
      highlight: false,
    },
    {
      name: 'Rider Pack',
      price: '$149',
      period: '5 classes',
      features: ['5 class credits', 'Bike + shoes included', 'Performance tracking', 'Priority booking', 'Valid 60 days'],
      highlight: true,
    },
    {
      name: 'Unlimited',
      price: '$199',
      period: 'per month',
      features: ['Unlimited classes', 'Bike + shoes included', 'Monthly metrics report', 'Community events', 'Guest passes (2/mo)'],
      highlight: false,
    },
  ],
};
